### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by amur-tiger** [NekiCat/yu-gi-oh#15]
Numbers are formatted a bit weird. Most notably, 0 (zero) and o (little O) are printed the same. This might be a font issue.

![ef44242e-4741-415a-933c-b240ec1107db](https://user-images.githubusercontent.com/7508551/27992733-2d0645ee-649b-11e7-88b0-0fe703ad5816.jpg)

**Comment by MisterSpinne** [comment]
No bug, as identical to original. It just looks very weird when examined out of context.
